name: Pack to NuGet

on:
  workflow_dispatch:
    inputs:
      Upload_to_NuGet:
        description: 'Upload to NuGet'
        default: true
        type: boolean
      Ursa:
        description: 'Pack Ursa'
        default: true
        type: boolean
      Ursa_Themes_Semi:
        description: 'Pack Ursa.Themes.Semi'
        default: true
        type: boolean
      PrismExtension:
        description: 'Pack Prism Extension'
        default: false
        type: boolean
      ReactiveUIExtension:
        description: 'Pack ReactiveUI Extension'
        default: false
        type: boolean
  workflow_call:
    inputs:
      Upload_to_NuGet:
        type: boolean
        default: false
      Ursa:
        default: true
        type: boolean
      Ursa_Themes_Semi:
        default: true
        type: boolean
      PrismExtension:
        default: false
        type: boolean
      ReactiveUIExtension:
        default: false
        type: boolean
    secrets: {}

jobs:
  Pack_to_NuGet:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Pack Ursa
        if: ${{ inputs.Ursa }}
        run: dotnet pack src/Ursa -o nugets

      - name: Pack Ursa.Themes.Semi
        if: ${{ inputs.Ursa_Themes_Semi }}
        run: dotnet pack src/Ursa.Themes.Semi -o nugets

      - name: Pack Prism Extension
        if: ${{ inputs.PrismExtension }}
        run: dotnet pack src/Ursa.PrismExtension -o nugets

      - name: Pack ReactiveUI Extension
        if: ${{ inputs.ReactiveUIExtension }}
        run: dotnet pack src/Ursa.ReactiveUIExtension -o nugets

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        if: ${{ inputs.Upload_to_NuGet }}
        with:
            user: ${{ secrets.NUGET_USER }}

      - name: NuGet push
        if: ${{ inputs.Upload_to_NuGet }}
        run: dotnet nuget push nugets/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: nugets
          path: nugets
        if: always()
