name: Release Tag

on:
  workflow_dispatch:
    inputs:
      Upload_to_NuGet:
        description: 'Upload to NuGet'
        default: false
        type: boolean
      Ursa:
        description: 'Pack Ursa'
        default: true
        type: boolean
      Ursa_Themes_Semi:
        description: 'Pack Ursa.Themes.Semi'
        default: true
        type: boolean
      PrismExtension:
        description: 'Pack Prism Extension'
        default: false
        type: boolean
      ReactiveUIExtension:
        description: 'Pack ReactiveUI Extension'
        default: false
        type: boolean

jobs:
  nuget:
    uses: ./.github/workflows/pack.yml
    with:
      Upload_to_NuGet: ${{ inputs.Upload_to_NuGet }}
      Ursa: ${{ inputs.Ursa }}
      Ursa_Themes_Semi: ${{ inputs.Ursa_Themes_Semi }}
      PrismExtension: ${{ inputs.PrismExtension }}
      ReactiveUIExtension: ${{ inputs.ReactiveUIExtension }}

  publish:
    uses: ./.github/workflows/publish.yml

  draft-release:
    needs: [ nuget,publish ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0

      - name: Display structure of downloaded files
        run: ls -R

      - name: Zip artifacts
        run: |
          zip -rj Ursa.Demo.Desktop.win-x64.zip Ursa.Demo.Desktop.win-x64
          zip -rj Ursa.Demo.Desktop.win-x64.NativeAOT.zip Ursa.Demo.Desktop.win-x64.NativeAOT
          zip -rj Ursa.Demo.Desktop.linux-x64.zip Ursa.Demo.Desktop.linux-x64
          zip -rj Ursa.Demo.Desktop.linux-x64.NativeAOT.zip Ursa.Demo.Desktop.linux-x64.NativeAOT
          zip -rj Ursa.Demo.Desktop.osx-arm64.zip Ursa.Demo.Desktop.osx-arm64
          cd Ursa.Demo.Desktop.osx-arm64.NativeAOT
          zip -r ../Ursa.Demo.Desktop.osx-arm64.NativeAOT.zip .

      - name: Display structure of zipped files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          generate_release_notes: true
          draft: true
          files: |
            nugets/*.nupkg
            android-arm64/*.apk
            *.zip